overrides: "git://github.com/pyexcel/pyexcel-mobans!/mobanfile.yaml"
configuration:
  configuration: pyexcel_cli.yml
targets:
  - setup.py: setup.py
  - "docs/source/conf.py": "docs/source/conf.py.jj2"
  - .travis.yml: travis.yml.jj2
  - MANIFEST.in: MANIFEST.in.jj2
  - "tests/requirements.txt": "tests/requirements.txt"
  - README.rst: cli-README.rst.jj2
  - "docs/source/index.rst": cli-index.rst.jj2
  - .gitignore: gitignore.jj2  