sudo: false
dist: xenial
language: python
notifications:
  email: false
python:
  - &pypy2 pypy2.7-6.0
  - &pypy3 pypy3.5-6.0
  - 3.8
  - 3.7
  - 3.6
  - 3.5
  - 2.7

stages:
  - lint
  - moban
  - test


.lint: &lint
  git:
    submodules: false
  python: 3.6
  env:
    - MINREQ=0
  stage: lint
  script: make lint

.moban: &moban
  python: 3.6
  env:
    - MINREQ=0
  stage: moban
  install: pip install moban gitfs2 pypifs moban-jinja2-github moban-ansible
  script:
    - moban
    - git diff --exit-code

jobs:
  include:
    - *moban
    - *lint

stage: test

before_install:
  - if [[ -f min_requirements.txt && "$MINREQ" -eq 1 ]]; then
      mv min_requirements.txt requirements.txt ;
    fi
  - test ! -f rnd_requirements.txt ||
    pip install --no-deps -r rnd_requirements.txt
  - test ! -f rnd_requirements.txt || pip install -r rnd_requirements.txt ;
  - pip install -r tests/requirements.txt
script:
  - make test
after_success:
  codecov
